package MorphAnalyzer;
/*
 * PrefixFrame.java
 *
 * Created on May 16, 2005, 1:12 PM
 */

/**
 *
 * @author  Solomon See
 */
import java.util.*;
import DataStructures.*;
public class TrieListFrame extends javax.swing.JFrame {
    TrieListModel trieModel;
    /** Creates new form PrefixFrame */
    public TrieListFrame(Trie trie, String title) {
        initComponents();
        trieModel = new TrieListModel(trie);
        prefixList.setModel(trieModel);
        this.setTitle(title);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        prefixList = new javax.swing.JList();

        jScrollPane1.setViewportView(prefixList);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList prefixList;
    // End of variables declaration//GEN-END:variables
    
}
